use_frameworks!

target 'SocialSignIn-iOS_Tests' do
  pod 'SocialSignIn-iOS', :path => '../'
#  pod 'VK-ios-sdk'
#  pod 'GoogleSignIn'
#  pod 'FBSDKLoginKit'
#  pod 'Fabric'
#  pod 'TwitterKit'
#  pod 'FHSTwitterEngine', '~> 2.0'
#  pod 'InstagramLogin'
#  pod 'LinkedinSwift'

end
